### ISSUE TITLE
解决cookies被锁定的可行方案

### ISSUE THREAD

**Issue by verygoodlee** [zhifengle/gcookie#2]
使用[yt-dlp](https://github.com/yt-dlp/yt-dlp)下载视频时也会有cookies被锁定的问题，
解决方案是装一个这个插件 [yt-dlp-ChromeCookieUnlock](https://github.com/seproDev/yt-dlp-ChromeCookieUnlock)，
是python写的，基于 https://gist.github.com/csm10495/e89e660ffee0030e8ef410b793ad6a7e

里面又指向了另一个rust项目链接，其实是从rust翻译成python的
https://github.com/thewh1teagle/rookie/blob/02995bbbb692f775e12368e7fb2b728775c88ddd/rookie-rs/src/winapi.rs#L63

都是rust语言，移植过来应该很轻松

**Comment by zhifengle** [comment]
使用管理员权限 gcookie.exe 能读取被锁定cookie.
比如 `gcookie.exe bing.com -c edge`

如果你提到的方案不需要管理员权限，后面我可以改一下

**Comment by verygoodlee** [comment]
是的，不需要管理员权限

**Comment by verygoodlee** [comment]
不懂rust也瞎折腾出来了 
https://github.com/verygoodlee/gcookie/tree/test
改了下workflow，翻到最下面可下载Artifacts试用
https://github.com/verygoodlee/gcookie/actions/runs/11269579725

浏览器打开状态，无管理员权限，成功读取
![image](https://github.com/user-attachments/assets/b5f67b0e-87ca-4a81-858d-6fbe9c14f17b)

瞎折腾的，主打能用就行，就不PR了

**Comment by zhifengle** [comment]
https://github.com/zhifengle/gcookie/commit/0c9f858afe0c8ea429115142683436a47ffd21c5  这个功能加上了。
新的依赖库CI构建有问题。本地构建了一份
[gcookie.zip](https://github.com/user-attachments/files/17325262/gcookie.zip)

写这个工具时还没有 rookie 这个库，看了一下核心逻辑差不多，偷懒直接使用rookie。
