### ISSUE TITLE
从edge 的webView2 131版获取失败

### ISSUE THREAD

**Issue by bida2015** [zhifengle/gcookie#4]
前段时间130版本能正常获取，最近更新了webView2组件版本后，无法获取到了。

**Comment by zhifengle** [comment]
我这里是正常的 Windows11  Edge131。使用的管理员权限
`.\gcookie.exe -c Edge bing.com`

**Comment by bida2015** [comment]
> 我这里是正常的 Windows11 Edge131。使用的管理员权限 `.\gcookie.exe -c Edge bing.com`

是的，在默认浏览器下是能正常读取到，但是使用webView2组件框架打开网址，并且指定在某个配置目录内，却获取不到的。

**Comment by zhifengle** [comment]
错误信息是不是 “No cookies found”。如果是看看配置目录的上一层是否有 “Local State” 这个文件。浏览器的“Local State”是在配置目录的上一层。找不到 `Local State` 文件会导致报错

**Comment by bida2015** [comment]
> 错误信息是不是 “No cookies found”。如果是看看配置目录的上一层是否有 “Local State” 这个文件。浏览器的“Local State”是在配置目录的上一层。找不到 `Local State` 文件会导致报错

是的，提示信息是：No cookies found.

但上层的Local State文件是存在的。

传入路径: "C:\\Users\\Administrator\\AppData\\Local\\testWebView2\\EBWebView\\Default"
C:\Users\Administrator\AppData\Local\testWebView2\EBWebView\Default\Network\Cookies 【存在】
C:\Users\Administrator\AppData\Local\testWebView2\EBWebView\Local State 【存在】


DB Browser for SQLite打开\Network\Cookies后显示：
value列全为空，encrypted_value列是BLOD，选中后它是个二进制，应该是加密的。

这是用tauri创建的浏览器窗口，之前默认并未加密的，奇怪了。

**Comment by zhifengle** [comment]
有可能是加密的密钥变了
Chrome、Edge的加密密钥在  elevation_service.exe   里面
我这里版本 131.0.2903.99 EdgeWebView 和 EdgeCore  的 `elevation_service.exe`  sha256 是 649f0de244669cafaccd5889968d9d32e7fd090646f5fc8ae6706b8155d0e0f7

如果webview2应用对应的elevation_service.exe sha256不同，有可能是密钥变了

**Comment by bida2015** [comment]
EdgeWebView 和 EdgeCore 的 elevation_service.exe  的sha256跟你的版本都是一样的：649f0de244669cafaccd5889968d9d32e7fd090646f5fc8ae6706b8155d0e0f7

**Comment by zhifengle** [comment]
原因我大概找到了，解决方法暂时没找到。

webview2 里面的配置里面 Network\Cookies  encrypted_value列是BLOD的前三位是 hex 76 31 30 就是  `v10`
Edge的Cookies encrypted_value列是BLOD的前三位是 `v20`

**Comment by bida2015** [comment]
> 原因我大概找到了，解决方法暂时没找到。
> 
> webview2 里面的配置里面 Network\Cookies encrypted_value列是BLOD的前三位是 hex 76 31 30 就是 `v10` Edge的Cookies encrypted_value列是BLOD的前三位是 `v20`

既然能定位到原因了，那离解决方案就不远了，期待一下。
